/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend.tools;

import frontend.dialog.ColorChooserDialog;
import java.awt.Color;

/**
 *
 * @author nickz
 */
public class ColorToolbar extends javax.swing.JPanel {

    private static Color globalColor;
    private java.awt.Frame parent;

    public static Color getGlobalColor() {
        return globalColor;
    }

    public ColorToolbar() {
        initComponents();
        updateColor();
    }

    public ColorToolbar(java.awt.Frame parent) {
        this.parent = parent;
        initComponents();
        updateColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redSpinner = new javax.swing.JSpinner();
        greenSpinner = new javax.swing.JSpinner();
        blueSpinner = new javax.swing.JSpinner();
        redSlider = new javax.swing.JSlider();
        greenSlider = new javax.swing.JSlider();
        colorBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        blueSlider = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(200, 200));

        redSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        redSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                redSpinnerStateChanged(evt);
            }
        });

        greenSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        greenSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                greenSpinnerStateChanged(evt);
            }
        });

        blueSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        blueSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                blueSpinnerStateChanged(evt);
            }
        });

        redSlider.setMaximum(255);
        redSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        redSlider.setValue(0);
        redSlider.setMinimumSize(new java.awt.Dimension(36, 20));
        redSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                redSliderStateChanged(evt);
            }
        });

        greenSlider.setMaximum(255);
        greenSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        greenSlider.setValue(0);
        greenSlider.setMaximumSize(new java.awt.Dimension(32767, 20));
        greenSlider.setMinimumSize(new java.awt.Dimension(36, 20));
        greenSlider.setPreferredSize(new java.awt.Dimension(200, 20));
        greenSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                greenSliderStateChanged(evt);
            }
        });

        colorBtn.setBackground(new java.awt.Color(255, 255, 255));
        colorBtn.setBorder(null);
        colorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Red");

        jLabel2.setText("Green");

        blueSlider.setMaximum(255);
        blueSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        blueSlider.setValue(0);
        blueSlider.setPreferredSize(new java.awt.Dimension(200, 20));
        blueSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                blueSliderStateChanged(evt);
            }
        });

        jLabel3.setText("Blue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(redSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(redSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(greenSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(greenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(redSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(greenSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(redSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(greenSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(blueSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void redSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_redSliderStateChanged
        // TODO add your handling code here:
        redSpinner.setValue(redSlider.getValue());
        updateColor();
    }//GEN-LAST:event_redSliderStateChanged

    private void redSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_redSpinnerStateChanged
        // TODO add your handling code here:
        redSlider.setValue((int) redSpinner.getValue());
        updateColor();
    }//GEN-LAST:event_redSpinnerStateChanged

    private void greenSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_greenSliderStateChanged
        // TODO add your handling code here:
        greenSpinner.setValue(greenSlider.getValue());
        updateColor();
    }//GEN-LAST:event_greenSliderStateChanged

    private void greenSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_greenSpinnerStateChanged
        // TODO add your handling code here:
        greenSlider.setValue((int) greenSpinner.getValue());
        updateColor();
    }//GEN-LAST:event_greenSpinnerStateChanged

    private void blueSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_blueSliderStateChanged
        // TODO add your handling code here:
        blueSpinner.setValue(blueSlider.getValue());
        updateColor();
    }//GEN-LAST:event_blueSliderStateChanged

    private void blueSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_blueSpinnerStateChanged
        // TODO add your handling code here:
        blueSlider.setValue((int) blueSpinner.getValue());
        updateColor();
    }//GEN-LAST:event_blueSpinnerStateChanged

    private void colorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorBtnActionPerformed
        // TODO add your handling code here:
        Color c = ColorChooserDialog.showDialog(parent, this.colorBtn.getBackground());
        this.colorBtn.setBackground(c);
        this.redSpinner.setValue(c.getRed());
        this.greenSpinner.setValue(c.getGreen());
        this.blueSpinner.setValue(c.getBlue());
    }//GEN-LAST:event_colorBtnActionPerformed

    private void updateColor() {
        globalColor = new Color((int) redSpinner.getValue(), (int) greenSpinner.getValue(), (int) blueSpinner.getValue());
        colorBtn.setBackground(globalColor);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider blueSlider;
    private javax.swing.JSpinner blueSpinner;
    private javax.swing.JButton colorBtn;
    private javax.swing.JSlider greenSlider;
    private javax.swing.JSpinner greenSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider redSlider;
    private javax.swing.JSpinner redSpinner;
    // End of variables declaration//GEN-END:variables
}
