/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

/**
 *
 * @author nickz
 */
public class MainView extends javax.swing.JFrame {

    private final MenuController controller;

    /**
     * Creates new form MainView
     *
     * @param controller A reference to the control logic for this view.
     */
    public MainView(MenuController controller) {
        this.controller = controller;
        System.out.println("MainView()");
        initComponents();
        initHandlers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        toolbar = new frontend.toolbar.Toolbar();
        subToolbarSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        documentTabbedPane = new frontend.DocumentPane();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        recentMenu = new javax.swing.JMenu();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        recentClearMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        closeMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        importMenuItem = new javax.swing.JMenuItem();
        exportMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        preferencesMenuItem = new javax.swing.JMenuItem();
        shortcutSettingsMenuItem = new javax.swing.JMenuItem();
        tabletSettingsMenuItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        quitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoMenuItem = new javax.swing.JMenuItem();
        redoMenuItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        clearMenuItem = new javax.swing.JMenuItem();
        fillMenuItem = new javax.swing.JMenuItem();
        advancedFillMenuItem = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        tonalCorrectionMenu = new javax.swing.JMenu();
        transformMenu = new javax.swing.JMenu();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        changeResolutionMenuItem = new javax.swing.JMenuItem();
        changeCanvasSizeMenuItem = new javax.swing.JMenuItem();
        cropMenuItem = new javax.swing.JMenuItem();
        layerPropertiesMenuItem = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        bufferMenuItem = new javax.swing.JMenuItem();
        imageMenu = new javax.swing.JMenu();
        layerMenu = new javax.swing.JMenu();
        newLayerMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        newLayerFolderMenuItem = new javax.swing.JMenuItem();
        duplicateLayerMenuItem = new javax.swing.JMenuItem();
        deleteLayerMenuItem = new javax.swing.JMenuItem();
        selectionMenu = new javax.swing.JMenu();
        selectAllMenuItem = new javax.swing.JMenuItem();
        deselectMenuItem = new javax.swing.JMenuItem();
        invertSelectionMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        collaborateMenu = new javax.swing.JMenu();
        connectMenuItem = new javax.swing.JMenuItem();
        disconnectMenuItem = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        connectionSettingsMenuItem = new javax.swing.JMenuItem();
        animationMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        gfxMenu = new javax.swing.JMenu();
        windowMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jraw");
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("mainframe"); // NOI18N

        mainPanel.setFocusable(false);
        mainPanel.setPreferredSize(new java.awt.Dimension(1360, 720));

        toolbar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        toolbar.setFloatable(false);
        toolbar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        toolbar.setRollover(true);
        toolbar.setToolTipText("");
        toolbar.setFocusable(false);
        toolbar.setMinimumSize(new java.awt.Dimension(40, 40));
        toolbar.setPreferredSize(new java.awt.Dimension(40, 0));

        subToolbarSplitPane.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        subToolbarSplitPane.setDividerLocation(super.getSize().height / 2);
        subToolbarSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        subToolbarSplitPane.setFocusable(false);

        jPanel1.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        subToolbarSplitPane.setTopComponent(jPanel1);

        jPanel2.setFocusable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        subToolbarSplitPane.setRightComponent(jPanel2);

        documentTabbedPane.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED)));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(subToolbarSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(documentTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(subToolbarSplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(documentTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainMenuBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mainMenuBar.setFocusable(false);
        mainMenuBar.setMaximumSize(new java.awt.Dimension(0, 40));
        mainMenuBar.setPreferredSize(new java.awt.Dimension(109, 30));

        fileMenu.setText("File");
        fileMenu.setFocusable(false);

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setText("New...");
        fileMenu.add(newMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setText("Open...");
        fileMenu.add(openMenuItem);

        recentMenu.setText("Recent Files");
        recentMenu.add(jSeparator11);

        recentClearMenuItem.setText("Clear Recent FIles");
        recentMenu.add(recentClearMenuItem);

        fileMenu.add(recentMenu);
        fileMenu.add(jSeparator1);

        closeMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        closeMenuItem.setText("Close File");
        fileMenu.add(closeMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        saveAsMenuItem.setText("Save As...");
        fileMenu.add(saveAsMenuItem);
        fileMenu.add(jSeparator2);

        importMenuItem.setText("Import...");
        fileMenu.add(importMenuItem);

        exportMenuItem.setText("Export...");
        fileMenu.add(exportMenuItem);
        fileMenu.add(jSeparator3);

        preferencesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        preferencesMenuItem.setText("Preferences...");
        fileMenu.add(preferencesMenuItem);

        shortcutSettingsMenuItem.setText("Shortcut Settings...");
        fileMenu.add(shortcutSettingsMenuItem);

        tabletSettingsMenuItem.setText("Tablet Settings...");
        fileMenu.add(tabletSettingsMenuItem);
        fileMenu.add(jSeparator4);

        quitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        quitMenuItem.setText("Quit");
        fileMenu.add(quitMenuItem);

        mainMenuBar.add(fileMenu);

        editMenu.setText("Edit");
        editMenu.setFocusable(false);

        undoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        undoMenuItem.setText("Undo");
        editMenu.add(undoMenuItem);

        redoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        redoMenuItem.setText("Redo");
        editMenu.add(redoMenuItem);
        editMenu.add(jSeparator5);

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);
        editMenu.add(jSeparator6);

        clearMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        clearMenuItem.setText("Clear");
        editMenu.add(clearMenuItem);

        fillMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.ALT_MASK));
        fillMenuItem.setText("Fill");
        editMenu.add(fillMenuItem);

        advancedFillMenuItem.setText("Advanced Fill...");
        editMenu.add(advancedFillMenuItem);
        editMenu.add(jSeparator7);

        tonalCorrectionMenu.setText("Tonal Correction");
        editMenu.add(tonalCorrectionMenu);

        transformMenu.setText("Transform");
        editMenu.add(transformMenu);
        editMenu.add(jSeparator8);

        changeResolutionMenuItem.setText("Change Resolution...");
        editMenu.add(changeResolutionMenuItem);

        changeCanvasSizeMenuItem.setText("Change Canvas Size...");
        editMenu.add(changeCanvasSizeMenuItem);

        cropMenuItem.setText("Crop");
        editMenu.add(cropMenuItem);

        layerPropertiesMenuItem.setText("Layer Properties...");
        editMenu.add(layerPropertiesMenuItem);
        editMenu.add(jSeparator9);

        bufferMenuItem.setText("Buffer...");
        editMenu.add(bufferMenuItem);

        mainMenuBar.add(editMenu);

        imageMenu.setText("Image");
        mainMenuBar.add(imageMenu);

        layerMenu.setText("Layer");
        layerMenu.setFocusable(false);

        newLayerMenu.setText("New Layer");

        jMenuItem2.setText("jMenuItem2");
        newLayerMenu.add(jMenuItem2);

        layerMenu.add(newLayerMenu);

        newLayerFolderMenuItem.setText("New Layer Folder");
        layerMenu.add(newLayerFolderMenuItem);

        duplicateLayerMenuItem.setText("Duplicate Layer");
        layerMenu.add(duplicateLayerMenuItem);

        deleteLayerMenuItem.setText("Delete Layer");
        layerMenu.add(deleteLayerMenuItem);

        mainMenuBar.add(layerMenu);

        selectionMenu.setText("Selection");
        selectionMenu.setFocusable(false);

        selectAllMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        selectAllMenuItem.setText("Select All");
        selectionMenu.add(selectAllMenuItem);

        deselectMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deselectMenuItem.setText("Deselect");
        selectionMenu.add(deselectMenuItem);

        invertSelectionMenuItem.setText("Invert Selection");
        selectionMenu.add(invertSelectionMenuItem);

        mainMenuBar.add(selectionMenu);

        viewMenu.setText("View");
        viewMenu.setFocusable(false);
        mainMenuBar.add(viewMenu);

        collaborateMenu.setText("Collaborate");

        connectMenuItem.setText("Connect...");
        collaborateMenu.add(connectMenuItem);

        disconnectMenuItem.setText("Disconnect");
        collaborateMenu.add(disconnectMenuItem);
        collaborateMenu.add(jSeparator10);

        connectionSettingsMenuItem.setText("Connection Settings...");
        collaborateMenu.add(connectionSettingsMenuItem);

        mainMenuBar.add(collaborateMenu);

        animationMenu.setText("Animation");
        animationMenu.setFocusable(false);

        jMenuItem1.setText("jMenuItem1");
        animationMenu.add(jMenuItem1);

        mainMenuBar.add(animationMenu);

        gfxMenu.setText("GFX");
        gfxMenu.setFocusable(false);
        mainMenuBar.add(gfxMenu);

        windowMenu.setText("Window");

        jMenuItem3.setText("jMenuItem3");
        windowMenu.add(jMenuItem3);

        mainMenuBar.add(windowMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initHandlers() {
        this.newMenuItem.addActionListener(controller.new NewFileAction());
        this.quitMenuItem.addActionListener(controller.new QuitAction());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem advancedFillMenuItem;
    private javax.swing.JMenu animationMenu;
    private javax.swing.JMenuItem bufferMenuItem;
    private javax.swing.JMenuItem changeCanvasSizeMenuItem;
    private javax.swing.JMenuItem changeResolutionMenuItem;
    private javax.swing.JMenuItem clearMenuItem;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JMenu collaborateMenu;
    private javax.swing.JMenuItem connectMenuItem;
    private javax.swing.JMenuItem connectionSettingsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cropMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteLayerMenuItem;
    private javax.swing.JMenuItem deselectMenuItem;
    private javax.swing.JMenuItem disconnectMenuItem;
    public frontend.DocumentPane documentTabbedPane;
    private javax.swing.JMenuItem duplicateLayerMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exportMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fillMenuItem;
    private javax.swing.JMenu gfxMenu;
    private javax.swing.JMenu imageMenu;
    private javax.swing.JMenuItem importMenuItem;
    private javax.swing.JMenuItem invertSelectionMenuItem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JMenu layerMenu;
    private javax.swing.JMenuItem layerPropertiesMenuItem;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem newLayerFolderMenuItem;
    private javax.swing.JMenu newLayerMenu;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem preferencesMenuItem;
    private javax.swing.JMenuItem quitMenuItem;
    private javax.swing.JMenuItem recentClearMenuItem;
    private javax.swing.JMenu recentMenu;
    private javax.swing.JMenuItem redoMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JMenuItem selectAllMenuItem;
    private javax.swing.JMenu selectionMenu;
    private javax.swing.JMenuItem shortcutSettingsMenuItem;
    private javax.swing.JSplitPane subToolbarSplitPane;
    private javax.swing.JMenuItem tabletSettingsMenuItem;
    private javax.swing.JMenu tonalCorrectionMenu;
    private frontend.toolbar.Toolbar toolbar;
    private javax.swing.JMenu transformMenu;
    private javax.swing.JMenuItem undoMenuItem;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JMenu windowMenu;
    // End of variables declaration//GEN-END:variables

}
